GEMINI_API_KEY ="gemini-key"

[gcp_service_account]
type = "service_account"
project_id = "tailor-talk-agent"
private_key_id = "448fcde5f672507cc0d4c2fc4e23aaeb4371190b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC1SZn6Wvo+ff0C
BpY/RJK/dUSKcIGuLQ3rLoLpdztuPHaNVohe5E4J+9BCm+dlckwUgcoATefe1lNh
tSD2xw8/YljcZTShEQO15P14VPiNJH8fT0LCU6eZYdv/9o9dQe+a1AFuOSq3Lzqa
dTuddnK7dwAiSl0iHA6nN984iOS1Knpc5TMwyZiInCyhNNdhZFKOeqGA+ZDNoG1W
hUBmibgN80EFwCXhEl7+M68CFbenfrRPXH743qCqBtYBgMmBoFCvVl7MNm5zItgR
Xjxp5pUTM9kTv+WQFFhHt7C61jb1+x3sxAPxoLqGMXEGoiXmaC/oG/g/xwB+exfP
kckSmYDNAgMBAAECggEAHasEJzfc1L3PGlYEICoDfxA8rZBQdLX8XWTw+S6xW+7K
swI6kpb324PplwEHKy+7mi6MZaTaQbpfDnIzSReWG/gnFTh91q8fZZTqU1dKjuSu
ZiwVP5KrrrsYYykRWMB56yNvcX+rCSwSQeVWIoSYLaxBqhrz52lij4SiBBFJJomc
uce3EOPa0uFJtH02AicArq5jf+/EqIHJQ15vnRXYGT7tKDIvW3DikkKvQ/m0I2f6
T+SFpxiB58KQZAfaRue5HDkOZeFRnaxpRVi8GqeeSHOOrktFrKhEiIx272h0ZQvo
/MHeoPmDL/LH0VTUD2NmQ2yaDAxsgwUVP6kNEY9BOQKBgQDj5HpX673LogpByKaF
D2tzO9Dtbmgrc4BW02CrqWERnIUn010IDgGeANAkXzolnnIqYPMa95j4yUHtJbLt
gYDTd6iz+nQsGL67ckjnmuFTXBQv+cVVxh7iB6kL8i//23f+KhIb1kopgDdEBES9
M5aF5mRzHqbw0o31gNlc05MgtQKBgQDLpZvPMgxfxbrL+5du/vlGrs0Yv/H/QJAl
YP/oJ31kb/xDkrnRrHaxE+Qfa088iMfZzkOkEPlYyz8B5RPOSyeoa+fSKzVWVmeA
pNXpq3Teg7U4UABNitzdzcv6bCjum5HwnAZW9SyjC5lhjEmyI1HxpDm/3gAnK/+m
Xky1fDwmuQKBgBxg2j9SktrlvcM9WkcdiXLbEwROCFjI1EV7owEdYYIQ7J/t+RrE
q7ziOwkcdqAyn+LZGczU4k6wuS3v0N00kDdFIlPvL0JCfpXXAG8e4UpBIB5tSv6I
YlYhQBLFwOZqjQGweXrP74JFfhxRL8Ijx227J+0R9xXsElNtDSQ7EIo1AoGADvlv
eo3QkR5F/QfT+8pt4/+ofyBmGAHUV5tJVfXJZ6BAaWuZlExdMeonhRPr8KSSJXbg
TGkfHKNdT7NbgHjQQrckhbS9qEqUM8ZrIFKGNnJy2eAwFYOXeAvQ6uoXHGx+D7Y5
VR2UGa0Zqy2YoautM9qCkJQvaLH4i3A1rcaj2akCgYBzXWj9rTIBOtg8jU8BRkte
CPccil1Vci6TsioQwIYNFPhq/ae+06zid+9By6LA9U1shxq3mfDLeCSzXaX+/pq0
XxZD/9LMoAnUaDEIQPy2IZ8kQ+nCObGUYB+aOWrNZu6xJ+eb9UIPvoPmVFY0kdaZ
K/NE4ZXg1n9XR1oHWEbdhQ==
-----END PRIVATE KEY-----"""
client_email = "tailor-talk-agent@tailor-talk-agent.iam.gserviceaccount.com"
client_id = "112677514497196598340"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/tailor-talk-agent%40tailor-talk-agent.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
